<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Npgsql" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atlas.Kernel\Atlas.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Domain\Atlas.Modules.Ledger.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Application\Atlas.Modules.Ledger.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Infrastructure\Atlas.Modules.Ledger.Infrastructure.csproj" />
  </ItemGroup>

</Project>
