<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Azurite" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Atlas.Kernel\Atlas.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Domain\Atlas.Modules.Ledger.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Application\Atlas.Modules.Ledger.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Infrastructure\Atlas.Modules.Ledger.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ledger\Contracts\Atlas.Modules.Ledger.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ingestion\Domain\Atlas.Modules.Ingestion.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ingestion\Application\Atlas.Modules.Ingestion.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ingestion\Infrastructure\Atlas.Modules.Ingestion.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Positions\Domain\Atlas.Modules.Positions.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Positions\Application\Atlas.Modules.Positions.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Positions\Infrastructure\Atlas.Modules.Positions.Infrastructure.csproj" />
  </ItemGroup>

</Project>
